### ISSUE TITLE
Can't send tokens

### ISSUE THREAD

**Issue by rustinmyeye** [ThierryM1212/ewc#1]
I'm trying to send tokens using ewc, but always get an invalid token id error. Sending erg works fine. I'd appreciate some help to figure out what I'm doing wrong... Thanks!! :)

This is what I'm trying:

ewc wallet-send -t 7a11a1789d9f2855303cf35823f426abf6c2770ce249cc0278e87629d75353df -u 1 -a 9iQS22vfWdF2N84Lvv9jgAMFGLyL7t17SWbHGEfaddaG7ZbL3fJ wallet password --sign --send

This is the error:

An error occured Invalid token Id
Cannot build the balance of the transaction

Here is the wallet details:

ewc wallet-get wallet password -b details                             
                                                                            
{
  "9hawyuf8SwtXGUWkdD8j5sZvCGfT2ZybBjqUYrzgiYtmCxjcqGx": {
    "amountERG": "0.4969",
    "tokens": [
      {
        "tokenId": "7a11a1789d9f2855303cf35823f426abf6c2770ce249cc0278e87629d75353df",
        "amount": "1"
      },
      {
        "tokenId": "ebb40ecab7bb7d2a935024100806db04f44c62c33ae9756cf6fc4cb6b9aa2d12",
        "amount": "50,000"
      }
    ]
  }
}

**Comment by ThierryM1212** [comment]
Thanks, there was a bug for tokens with 0 decimals, it should be addressed now.

https://github.com/ThierryM1212/ewc/commit/523eda01bfbef6dd697d3ad8bc4416a4dcb0adc9

**Comment by rustinmyeye** [comment]
Thanks! :)
